# Numpy Exercise

# Import the numpy package under the name np

In [1]:
import numpy as np

# 1. Print the numpy version

In [2]:
version = np.__version__

In [3]:
version

'2.3.4'

# 2. Print the configuration

In [4]:
np.show_config()

Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.1.4
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/build-env-hj_u2

# 3. Create a null vector of size 10

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 4. How to find the memory size of any array

In [6]:
arr = np.array([1,2,3])

In [7]:
arr.itemsize * arr.size

24

# 5. How to get the documentation of the numpy add function from the command line?

In [8]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

# 6. Create a null vector of size 10 but the fifth value which is 1

In [9]:
arr = np.zeros(10)

In [10]:
arr[4] = 1

In [11]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 7. Create a vector with values ranging from 10 to 49

In [12]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 8. Reverse a vector (first element becomes last)

In [13]:
arr1 = np.arange(0, 10)

In [14]:
arr1 = arr1[::-1]

In [15]:
arr1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# 9. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
arr2 = np.arange(0,9)

In [17]:
matrix = arr2.reshape(3,3)

In [18]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [19]:
arr3 = np.array([1,2,0,0,4,0])

In [20]:
np.nonzero(arr3)

(array([0, 1, 4]),)

# 11. Create a 3x3 identity matrix

In [21]:
ide = np.eye(3)

In [22]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 12. Create a 3x3x3 array with random values

In [23]:
arr4 = np.random.random((3,3,3))

In [24]:
arr4

array([[[0.05095155, 0.58456059, 0.28435127],
        [0.57022193, 0.99769089, 0.39010286],
        [0.0311635 , 0.61978842, 0.22024425]],

       [[0.22274769, 0.31897532, 0.56895534],
        [0.68819016, 0.54094267, 0.26977797],
        [0.13293286, 0.51464386, 0.2643509 ]],

       [[0.64981623, 0.10329981, 0.83453338],
        [0.31621388, 0.0280059 , 0.6798353 ],
        [0.65161263, 0.21482939, 0.42808763]]])

# 13. Create a 10x10 array with random values and find the minimum and maximum values

In [25]:
arr5 = np.random.random((10,10))

In [26]:
arr5

array([[0.6365434 , 0.95555473, 0.9197168 , 0.17074766, 0.88131585,
        0.34642256, 0.47851973, 0.77470351, 0.98684202, 0.77860754],
       [0.86412449, 0.86018415, 0.57722105, 0.17113948, 0.56361403,
        0.01528704, 0.61500021, 0.30900254, 0.47362546, 0.00573123],
       [0.04932643, 0.98222588, 0.84530024, 0.47793513, 0.86585206,
        0.06485287, 0.9237118 , 0.03734395, 0.73566597, 0.453167  ],
       [0.17952121, 0.96542702, 0.39638886, 0.48767679, 0.28078527,
        0.83699916, 0.95785402, 0.19104204, 0.99393357, 0.26390426],
       [0.79901377, 0.50341258, 0.26875749, 0.5259776 , 0.41074077,
        0.32017265, 0.81262315, 0.76210247, 0.00311775, 0.82285222],
       [0.08595725, 0.05527106, 0.84889074, 0.02584166, 0.58815124,
        0.28374944, 0.85483105, 0.16777395, 0.65064917, 0.12528274],
       [0.15904555, 0.20442521, 0.80256671, 0.60876559, 0.29171076,
        0.70749253, 0.37932741, 0.18404591, 0.45682374, 0.14829381],
       [0.05064189, 0.47597429, 0.2146793

In [27]:
np.max(arr5)

np.float64(0.993933569922391)

In [28]:
np.min(arr5)

np.float64(0.0031177507264450455)

# 14. Create a random vector of size 30 and find the mean value

In [29]:
arr6 = np.random.random(30)

In [30]:
arr6.mean()

np.float64(0.47689959895698936)

# 15. Create a 2d array with 1 on the border and 0 inside 

In [31]:
arr7 = np.ones((10,10))

In [32]:
arr7

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
arr7[1:-1, 1:-1] = 0

In [34]:
arr7

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 16. How to add a border (filled with 0's) around an existing array?

In [35]:
arr8 = np.ones((5,5))

In [36]:
arr8 = np.pad(arr8, pad_width = 1, mode='constant', constant_values=0)

In [37]:
arr8

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# 17

In [38]:
# What is the result of the following expression?
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1

In [39]:
#Answers:
#1. nan(Any arithmetic operation involving nan propagates nan)
#2. False(NaN is never equal to anything, including itself)
#3. False(Any comparison (>, <, >=, <=, ==) with nan returns False. nan is unordered — it doesn't fit anywhere on the number line, so it can't be "greater than" or "less than" anything either.)
#4. nan
#5. True(in for a set/dict uses hashing + identity check first, not ==. Since it's the same nan object being checked against itself, Python short-circuits via is before ever hitting __eq__. If you'd instead written np.nan in [float('nan')] (a different nan object, list not set), you'd get False, because list membership uses == linearly, and nan == nan is False.)
#6. False(never compare floats with ==)

# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [40]:
arr9 = np.diag(1+np.arange(4),k=-1)

In [41]:
arr9

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [42]:
A = np.zeros((8,8))

In [43]:
A

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
A[1::2, ::2] = 1

In [45]:
A[::2, 1::2] = 1

In [46]:
A

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [47]:
# another way

In [48]:
B = np.zeros((7,8))

In [49]:
B = np.fromfunction(lambda i,j: (i+j)%2, (7,8), dtype=int)

In [50]:
B

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [51]:
np.unravel_index(99,(6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

# 21. Create a checkerboard 8x8 matrix using the tile function

In [52]:
a = np.tile([[0,1],[1,0]], (4,4))

In [53]:
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 22. Normalize a 5x5 random matrix

In [54]:
a = np.random.random((5,5))

In [55]:
a = (a-np.mean(a))/(np.std(a))

In [56]:
a

array([[-0.70584222,  0.44186144,  1.11437069, -1.16406468, -0.75694592],
       [ 0.03635854,  0.33134447, -0.08192608,  0.80274636,  1.41509374],
       [-1.43131458, -0.49667487,  1.08066721, -1.53000955,  1.20313963],
       [-1.19430298, -0.95950911, -0.5594019 , -0.4887636 ,  1.3066502 ],
       [ 0.3491774 ,  1.5314908 ,  1.55522993, -0.83203112, -0.96734381]])

# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [57]:
color = np.dtype([("r",np.ubyte),
                 ("g",np.ubyte),
                 ("b",np.ubyte),
                 ("a",np.ubyte)])

# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [59]:
A = np.ones((5,3)) @ np.ones((3,2))

In [60]:
A

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [61]:
# another method

In [62]:
A = np.matmul(np.ones((5,3)), np.ones((3,2)))

In [63]:
A

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [64]:
A = np.arange(11)

In [65]:
A[(3 < A) & (A < 8)] *= -1

In [66]:
A

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

# 26. What is the output of the following script?

print(sum(range(5),-1))

from numpy import *

print(sum(range(5),-1))

In [67]:
#1. -1+0+1+2+3+4 = 9
#2. 1D array, axis = -1, means last row of the array(here it is a 1D array, so just sum the array)

# 27. Consider an integer vector Z, which of these expressions are legal?

In [68]:
# Z**Z -> illegal universally
# 2 << Z >> 2 -> illegal universally
# Z < -Z -> legal universally
# 1j*Z -> legal universally
# Z/1/1 -> legal universally(dtype changes from int to float due to '/'(true division).)
# Z<Z>Z -> illegal universally

# 29. How to round away from zero a float array ?