# Learning Numpy

In [1]:
import numpy as np

In [2]:
print("Pranshul")

Pranshul


In [3]:
myarr = np.array([[1,2,3,4]])

In [4]:
myarr

array([[1, 2, 3, 4]])

In [5]:
myarr[0,2] 

np.int64(3)

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr[0,2] = 5

In [9]:
myarr

array([[1, 2, 5, 4]])

# Array creation: Conversion from other python structures

In [10]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarray.dtype

dtype('int64')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [16]:
zeros = np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.dtype

dtype('float64')

In [19]:
zeros.shape

(2, 5)

In [20]:
rng = np.arange(10)

In [21]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
lspace = np.linspace(1,10,5)

In [23]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
lspace1 = np.linspace(1,4,4)

In [25]:
lspace1

array([1., 2., 3., 4.])

In [26]:
emp = np.empty((3,3))

In [27]:
emp

array([[ 1.14285714, -2.28571429,  0.57142857],
       [-2.28571429,  4.97142857, -1.54285714],
       [ 0.57142857, -1.54285714,  0.88571429]])

In [28]:
emp_like = np.empty_like(listarray)

In [29]:
emp_like

array([[4607825790175356065, 4612329389802726565, 4603322190547985584],
       [4612329389802726564, 4617283349392834114, 4609627230026304283],
       [4603322190547985580, 4609627230026304280, 4606153024599475605]])

In [30]:
ide = np.identity(3)

In [31]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
ide.shape

(3, 3)

In [33]:
 arr = np.arange(99)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr = arr.reshape(9,11)

In [36]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [37]:
arr = arr.ravel()

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.shape

(99,)

In [40]:
x = [[1,2,3],[4,5,6],[7,8,9],[11,12,13]]

In [41]:
arr = np.array(x)

In [42]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [43]:
arr.sum(axis=0)

array([23, 27, 31])

In [44]:
arr.sum(axis=1)

array([ 6, 15, 24, 36])

In [45]:
arr.T

array([[ 1,  4,  7, 11],
       [ 2,  5,  8, 12],
       [ 3,  6,  9, 13]])

In [46]:
arr.flat

In [47]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9
11
12
13


In [48]:
arr.ndim

2

In [49]:
arr.size

12

In [50]:
arr.nbytes

96

In [51]:
one = np.array([1,2,43,4,5])

In [52]:
one

array([ 1,  2, 43,  4,  5])

In [53]:
one.argmax()

np.int64(2)

In [54]:
one.argmin()

np.int64(0)

In [55]:
one.argsort()

array([0, 1, 3, 4, 2])

In [56]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [57]:
arr.argmin()

np.int64(0)

In [58]:
arr.argmax()

np.int64(11)

In [59]:
arr.argmax(axis = 0)

array([3, 3, 3])

In [60]:
arr.argmin(axis = 0)

array([0, 0, 0])

In [61]:
arr.argmin(axis = 1)

array([0, 0, 0, 0])

In [62]:
arr.argmax(axis = 1)

array([2, 2, 2, 2])

In [63]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [64]:
arr.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [65]:
arr.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [66]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [67]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [68]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 11],
       [12, 13]])

In [69]:
arr.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13]])

In [70]:
arr2 = [[1,2,3],[1,1,1],[2,3,2],[3,2,1]]

In [71]:
arr2

[[1, 2, 3], [1, 1, 1], [2, 3, 2], [3, 2, 1]]

In [72]:
arr3 = arr + arr2

In [73]:
arr3

array([[ 2,  4,  6],
       [ 5,  6,  7],
       [ 9, 11, 11],
       [14, 14, 14]])

In [74]:
arr4 = arr * arr2

In [75]:
arr4

array([[ 1,  4,  9],
       [ 4,  5,  6],
       [14, 24, 18],
       [33, 24, 13]])

In [76]:
np.sqrt(arr4)

array([[1.        , 2.        , 3.        ],
       [2.        , 2.23606798, 2.44948974],
       [3.74165739, 4.89897949, 4.24264069],
       [5.74456265, 4.89897949, 3.60555128]])

In [77]:
arr4.sum()

np.int64(155)

In [78]:
arr4.max()

np.int64(33)

In [79]:
arr4.min()

np.int64(1)

In [80]:
arr4.argmax()

np.int64(9)

In [81]:
np.where(arr4>13)

(array([2, 2, 2, 3, 3]), array([0, 1, 2, 0, 1]))

In [82]:
type(np.where(arr4>13))

tuple

In [83]:
np.count_nonzero(arr4)

np.int64(12)

In [84]:
np.nonzero(arr4)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [85]:
 arr4[0,0] = 0

In [86]:
arr4

array([[ 0,  4,  9],
       [ 4,  5,  6],
       [14, 24, 18],
       [33, 24, 13]])

In [87]:
np.nonzero(arr4)

(array([0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]),
 array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [88]:
np.count_nonzero(arr4)

np.int64(11)

In [89]:
import sys

In [90]:
py_ar = [0,2,4,6]

In [91]:
np_arr = np.array(py_ar)

In [92]:
np_arr

array([0, 2, 4, 6])

In [93]:
sys.getsizeof(1) * len(py_ar)

112

In [94]:
np_arr.itemsize * np_arr.size

32

In [95]:
np_ar.tolist()

NameError: name 'np_ar' is not defined