# Learning Numpy

In [1]:
import numpy as np

In [2]:
print("Pranshul")

Pranshul


In [3]:
myarr = np.array([[1,2,3,4]])

In [4]:
myarr

array([[1, 2, 3, 4]])

In [5]:
myarr[0,2] 

np.int64(3)

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr[0,2] = 5

In [9]:
myarr

array([[1, 2, 5, 4]])

# Array creation: Conversion from other python structures

In [10]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarray.dtype

dtype('int64')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

# Intrinsic Numpy array creation objects

In [16]:
zeros = np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.dtype

dtype('float64')

In [19]:
zeros.shape

(2, 5)

In [20]:
rng = np.arange(10)

In [21]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
lspace = np.linspace(1,10,5)

In [23]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
lspace1 = np.linspace(1,4,4)

In [25]:
lspace1

array([1., 2., 3., 4.])

In [26]:
emp = np.empty((3,3))

In [27]:
emp

array([[ 1.14285714, -2.28571429,  0.57142857],
       [-2.28571429,  4.97142857, -1.54285714],
       [ 0.57142857, -1.54285714,  0.88571429]])

In [28]:
emp_like = np.empty_like(listarray)

In [29]:
emp_like

array([[4607825790175356065, 4612329389802726565, 4603322190547985584],
       [4612329389802726564, 4617283349392834114, 4609627230026304283],
       [4603322190547985580, 4609627230026304280, 4606153024599475605]])

In [30]:
ide = np.identity(3)

In [31]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
ide.shape

(3, 3)

In [33]:
 arr = np.arange(99)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr = arr.reshape(9,11)

In [39]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [40]:
arr = arr.ravel()

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr.shape

(99,)