# Numpy Exercise

# Import the numpy package under the name np

In [1]:
import numpy as np

# 1. Print the numpy version

In [2]:
version = np.__version__

In [3]:
version

'2.3.4'

# 2. Print the configuration

In [4]:
np.show_config()

Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.1.4
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/build-env-hj_u2

# 3. Create a null vector of size 10

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 4. How to find the memory size of any array

In [6]:
arr = np.array([1,2,3])

In [7]:
arr.itemsize * arr.size

24

# 5. How to get the documentation of the numpy add function from the command line?

In [8]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

# 6. Create a null vector of size 10 but the fifth value which is 1

In [9]:
arr = np.zeros(10)

In [10]:
arr[4] = 1

In [11]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 7. Create a vector with values ranging from 10 to 49

In [12]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 8. Reverse a vector (first element becomes last)

In [13]:
arr1 = np.arange(0, 10)

In [14]:
arr1 = arr1[::-1]

In [15]:
arr1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# 9. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
arr2 = np.arange(0,9)

In [17]:
matrix = arr2.reshape(3,3)

In [18]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [19]:
arr3 = np.array([1,2,0,0,4,0])

In [20]:
np.nonzero(arr3)

(array([0, 1, 4]),)

# 11. Create a 3x3 identity matrix

In [21]:
ide = np.eye(3)

In [22]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 12. Create a 3x3x3 array with random values

In [23]:
arr4 = np.random.random((3,3,3))

In [24]:
arr4

array([[[0.95280855, 0.37171466, 0.62116249],
        [0.60040959, 0.71678518, 0.69149011],
        [0.47616587, 0.88003413, 0.71107665]],

       [[0.45369891, 0.01641619, 0.7299837 ],
        [0.14686363, 0.29768621, 0.12228665],
        [0.19840726, 0.11571606, 0.99640566]],

       [[0.56449342, 0.42129178, 0.29861826],
        [0.46542142, 0.35759724, 0.75345053],
        [0.24542113, 0.60923153, 0.20516082]]])

# 13. Create a 10x10 array with random values and find the minimum and maximum values

In [25]:
arr5 = np.random.random((10,10))

In [26]:
arr5

array([[0.03722813, 0.68533182, 0.28077753, 0.64898825, 0.95693341,
        0.73368992, 0.88740562, 0.85265833, 0.91450347, 0.88910124],
       [0.03255621, 0.00770695, 0.62306757, 0.20903649, 0.27499227,
        0.15498712, 0.2464186 , 0.38099295, 0.94210375, 0.69192224],
       [0.92585336, 0.83974502, 0.35159192, 0.36109767, 0.64988319,
        0.83573082, 0.26361048, 0.58174861, 0.99916674, 0.07170801],
       [0.38344873, 0.9679246 , 0.00571233, 0.04368737, 0.21921966,
        0.8267989 , 0.9987343 , 0.30564108, 0.5130259 , 0.08636512],
       [0.37444423, 0.82180971, 0.0135253 , 0.96500735, 0.15987939,
        0.34137107, 0.82181191, 0.79514833, 0.98755536, 0.20697836],
       [0.99612372, 0.30701664, 0.97065026, 0.76381474, 0.27275882,
        0.12182778, 0.59094077, 0.84801657, 0.89808242, 0.17151312],
       [0.04723479, 0.53339026, 0.9568419 , 0.28288659, 0.66701938,
        0.65187697, 0.74044789, 0.10098123, 0.63046367, 0.09253594],
       [0.77101943, 0.26772548, 0.9525002

In [27]:
np.max(arr5)

np.float64(0.9991667356410839)

In [28]:
np.min(arr5)

np.float64(0.005712326014659208)

# 14. Create a random vector of size 30 and find the mean value

In [29]:
arr6 = np.random.random(30)

In [30]:
arr6.mean()

np.float64(0.5083525370978857)

# 15. Create a 2d array with 1 on the border and 0 inside 

In [31]:
arr7 = np.ones((10,10))

In [32]:
arr7

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
arr7[1:-1, 1:-1] = 0

In [34]:
arr7

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 16. How to add a border (filled with 0's) around an existing array?

In [35]:
arr8 = np.ones((5,5))

In [36]:
arr8 = np.pad(arr8, pad_width = 1, mode='constant', constant_values=0)

In [37]:
arr8

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# 17

In [38]:
# What is the result of the following expression?
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1

In [39]:
#Answers:
#1. nan(Any arithmetic operation involving nan propagates nan)
#2. False(NaN is never equal to anything, including itself)
#3. False(Any comparison (>, <, >=, <=, ==) with nan returns False. nan is unordered — it doesn't fit anywhere on the number line, so it can't be "greater than" or "less than" anything either.)
#4. nan
#5. True(in for a set/dict uses hashing + identity check first, not ==. Since it's the same nan object being checked against itself, Python short-circuits via is before ever hitting __eq__. If you'd instead written np.nan in [float('nan')] (a different nan object, list not set), you'd get False, because list membership uses == linearly, and nan == nan is False.)
#6. False(never compare floats with ==)

# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [40]:
arr9 = np.diag(1+np.arange(4),k=-1)

In [41]:
arr9

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [42]:
A = np.zeros((8,8))

In [43]:
A

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
A[1::2, ::2] = 1

In [45]:
A[::2, 1::2] = 1

In [46]:
A

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [47]:
# another way

In [48]:
B = np.zeros((7,8))

In [49]:
B = np.fromfunction(lambda i,j: (i+j)%2, (7,8), dtype=int)

In [50]:
B

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [51]:
np.unravel_index(99,(6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

# 21. Create a checkerboard 8x8 matrix using the tile function

In [52]:
a = np.tile([[0,1],[1,0]], (4,4))

In [53]:
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 22. Normalize a 5x5 random matrix

In [54]:
a = np.random.random((5,5))

In [55]:
a = (a-np.mean(a))/(np.std(a))

In [56]:
a

array([[ 0.11532111, -1.50562534, -0.90164924, -1.16331408,  0.6185632 ],
       [ 0.59127327,  0.26096258, -0.34506447, -1.44746886,  0.92939755],
       [-1.12884189, -0.82598522, -0.78600218, -0.29699191,  0.93311004],
       [-0.32938236,  1.97870806,  0.69357303,  1.02649871, -0.4068605 ],
       [ 1.59265244, -0.61167238,  1.19415835, -1.33042232,  1.14506241]])

# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [57]:
color = np.dtype([("r",np.ubyte),
                 ("g",np.ubyte),
                 ("b",np.ubyte),
                 ("a",np.ubyte)])

# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [58]:
A = np.ones((5,3)) @ np.ones((3,2))

In [59]:
A

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [60]:
# another method

In [61]:
A = np.matmul(np.ones((5,3)), np.ones((3,2)))

In [62]:
A

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [63]:
A = np.arange(11)

In [64]:
A[(3 < A) & (A < 8)] *= -1

In [65]:
A

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

# 26. What is the output of the following script?

print(sum(range(5),-1))

from numpy import *

print(sum(range(5),-1))

In [66]:
#1. -1+0+1+2+3+4 = 9
#2. 1D array, axis = -1, means last row of the array(here it is a 1D array, so just sum the array)

# 27. Consider an integer vector Z, which of these expressions are legal?

In [67]:
# Z**Z -> illegal universally
# 2 << Z >> 2 -> illegal universally
# Z < -Z -> legal universally
# 1j*Z -> legal universally
# Z/1/1 -> legal universally(dtype changes from int to float due to '/'(true division).)
# Z<Z>Z -> illegal universally

# 29. How to round away from zero a float array ?

In [68]:
a = np.array([1.2, 1.8, -1.2, -1.8, 2.0, -2.0])

In [69]:
np.where(a>0, np.ceil(a), np.floor(a))

array([ 2.,  2., -2., -2.,  2., -2.])

In [70]:
# another method: 

In [71]:
np.sign(a)*np.ceil(np.abs(a))

array([ 2.,  2., -2., -2.,  2., -2.])

# 30. How to find common values between two arrays?

In [72]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)

In [73]:
np.intersect1d(a,b)

array([2, 4, 5, 6, 8])

# 31. How to get the dates of yesterday, today and tomorrow?

In [74]:
yesterday = np.datetime64('today') - np.timedelta64(1)

In [75]:
yesterday

np.datetime64('2026-09-05')

In [76]:
today     = np.datetime64('today')


In [77]:
today

np.datetime64('2026-09-06')

In [78]:
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [79]:
tomorrow

np.datetime64('2026-09-07')

# 32. How to get all the dates corresponding to the month of July 2016?

In [80]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

In [82]:
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

# 33. How to compute ((A+B)*(-A/2)) in place (without copy)? 

In [84]:
A = np.ones(3)*1

In [85]:
B = np.ones(3)*2

In [86]:
np.add(A,B, out=B)

array([3., 3., 3.])

In [87]:
np.divide(A,2, out = A)

array([0.5, 0.5, 0.5])

In [88]:
np.negative(A, out = A)

array([-0.5, -0.5, -0.5])

In [89]:
np.multiply(A,B, out = A)

array([-1.5, -1.5, -1.5])