# Numpy Exercise

# Import the numpy package under the name np

In [1]:
import numpy as np

# 1. Print the numpy version

In [2]:
version = np.__version__

In [3]:
version

'2.3.4'

# 2. Print the configuration

In [4]:
np.show_config()

Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.1.4
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/build-env-hj_u2

# 3. Create a null vector of size 10

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 4. How to find the memory size of any array

In [6]:
arr = np.array([1,2,3])

In [7]:
arr.itemsize * arr.size

24

# 5. How to get the documentation of the numpy add function from the command line?

In [8]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

# 6. Create a null vector of size 10 but the fifth value which is 1

In [9]:
arr = np.zeros(10)

In [10]:
arr[4] = 1

In [11]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 7. Create a vector with values ranging from 10 to 49

In [12]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 8. Reverse a vector (first element becomes last)

In [13]:
arr1 = np.arange(0, 10)

In [14]:
arr1 = arr1[::-1]

In [15]:
arr1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# 9. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
arr2 = np.arange(0,9)

In [17]:
matrix = arr2.reshape(3,3)

In [18]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [19]:
arr3 = np.array([1,2,0,0,4,0])

In [20]:
np.nonzero(arr3)

(array([0, 1, 4]),)

# 11. Create a 3x3 identity matrix

In [21]:
ide = np.eye(3)

In [22]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 12. Create a 3x3x3 array with random values

In [23]:
arr4 = np.random.random((3,3,3))

In [24]:
arr4

array([[[0.59802573, 0.81193186, 0.13729998],
        [0.00876906, 0.17644175, 0.8644349 ],
        [0.91034229, 0.28177546, 0.59583364]],

       [[0.84200984, 0.60753556, 0.3236332 ],
        [0.65045784, 0.49046755, 0.79474712],
        [0.9370938 , 0.1135793 , 0.331413  ]],

       [[0.54616834, 0.26072932, 0.33797457],
        [0.62916607, 0.48320445, 0.86364116],
        [0.48443099, 0.84123486, 0.45786583]]])

# 13. Create a 10x10 array with random values and find the minimum and maximum values

In [25]:
arr5 = np.random.random((10,10))

In [26]:
arr5

array([[0.50033372, 0.41948809, 0.15705773, 0.21807563, 0.57842398,
        0.17212884, 0.8936288 , 0.89035254, 0.01977552, 0.97689616],
       [0.8233498 , 0.2423855 , 0.03975708, 0.14441569, 0.417067  ,
        0.93284796, 0.87550972, 0.10236422, 0.47556151, 0.08209399],
       [0.64555736, 0.32962042, 0.88881955, 0.03091739, 0.48220833,
        0.81835301, 0.75832839, 0.22860087, 0.99689828, 0.45644862],
       [0.86274474, 0.8535594 , 0.30438727, 0.83205429, 0.75496061,
        0.29461748, 0.51296125, 0.99515609, 0.14469001, 0.05411135],
       [0.72215632, 0.75035489, 0.62853852, 0.94880959, 0.34594231,
        0.74916729, 0.41827838, 0.72550049, 0.01526427, 0.94420999],
       [0.41113782, 0.32875312, 0.15928357, 0.36278118, 0.20456724,
        0.72057964, 0.60296271, 0.53169368, 0.8822113 , 0.10926176],
       [0.09960747, 0.54401841, 0.09507832, 0.20806669, 0.18666149,
        0.76800809, 0.25933692, 0.17156176, 0.38853425, 0.51143951],
       [0.20321561, 0.13740446, 0.3109143

In [27]:
np.max(arr5)

np.float64(0.9968982803828621)

In [28]:
np.min(arr5)

np.float64(0.015264274261085342)

# 14. Create a random vector of size 30 and find the mean value

In [29]:
arr6 = np.random.random(30)

In [30]:
arr6.mean()

np.float64(0.5587568912983397)

# 15. Create a 2d array with 1 on the border and 0 inside 

In [31]:
arr7 = np.ones((10,10))

In [32]:
arr7

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
arr7[1:-1, 1:-1] = 0

In [34]:
arr7

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 16. How to add a border (filled with 0's) around an existing array?

In [35]:
arr8 = np.ones((5,5))

In [36]:
arr8 = np.pad(arr8, pad_width = 1, mode='constant', constant_values=0)

In [37]:
arr8

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# 17

In [39]:
# What is the result of the following expression?
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1

In [40]:
#Answers:
#1. nan(Any arithmetic operation involving nan propagates nan)
#2. False(NaN is never equal to anything, including itself)
#3. False(Any comparison (>, <, >=, <=, ==) with nan returns False. nan is unordered — it doesn't fit anywhere on the number line, so it can't be "greater than" or "less than" anything either.)
#4. nan
#5. True(in for a set/dict uses hashing + identity check first, not ==. Since it's the same nan object being checked against itself, Python short-circuits via is before ever hitting __eq__. If you'd instead written np.nan in [float('nan')] (a different nan object, list not set), you'd get False, because list membership uses == linearly, and nan == nan is False.)
#6. False(never compare floats with ==)