# Numpy Exercise

# Import the numpy package under the name np

In [1]:
import numpy as np

# 1. Print the numpy version

In [2]:
version = np.__version__

In [3]:
version

'2.3.4'

# 2. Print the configuration

In [4]:
np.show_config()

Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.1.4
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/y6/nj790rtn62lfktb1sh__79hc0000gn/T/build-env-hj_u2

# 3. Create a null vector of size 10

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 4. How to find the memory size of any array

In [6]:
arr = np.array([1,2,3])

In [7]:
arr.itemsize * arr.size

24

# 5. How to get the documentation of the numpy add function from the command line?

In [8]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

# 6. Create a null vector of size 10 but the fifth value which is 1

In [9]:
arr = np.zeros(10)

In [10]:
arr[4] = 1

In [11]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 7. Create a vector with values ranging from 10 to 49

In [12]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 8. Reverse a vector (first element becomes last)

In [13]:
arr1 = np.arange(0, 10)

In [14]:
arr1 = arr1[::-1]

In [15]:
arr1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# 9. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
arr2 = np.arange(0,9)

In [17]:
matrix = arr2.reshape(3,3)

In [18]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [19]:
arr3 = np.array([1,2,0,0,4,0])

In [20]:
np.nonzero(arr3)

(array([0, 1, 4]),)

# 11. Create a 3x3 identity matrix

In [21]:
ide = np.eye(3)

In [22]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 12. Create a 3x3x3 array with random values

In [23]:
arr4 = np.random.random((3,3,3))

In [24]:
arr4

array([[[0.02660789, 0.58306167, 0.86414042],
        [0.72711298, 0.26165304, 0.35812373],
        [0.8223263 , 0.77434606, 0.28648308]],

       [[0.83491074, 0.65436497, 0.22278546],
        [0.32956001, 0.85844197, 0.83151302],
        [0.97719433, 0.7628675 , 0.27104536]],

       [[0.46599917, 0.58433793, 0.50497227],
        [0.13261797, 0.97832012, 0.96960541],
        [0.71227899, 0.85537841, 0.48052964]]])

# 13. Create a 10x10 array with random values and find the minimum and maximum values

In [25]:
arr5 = np.random.random((10,10))

In [26]:
arr5

array([[1.88519174e-01, 7.21904203e-01, 1.14222648e-01, 3.24402815e-01,
        2.86338580e-01, 7.01747569e-01, 1.54647037e-01, 7.31253131e-01,
        2.19105531e-01, 3.86376233e-01],
       [2.11029229e-01, 6.77544399e-01, 6.01599579e-01, 8.35007387e-01,
        2.72244938e-01, 7.89622449e-01, 4.41877242e-01, 4.27539587e-02,
        4.38647885e-01, 7.16935146e-01],
       [9.41811924e-01, 9.80516562e-01, 4.67250917e-01, 3.34625250e-01,
        5.81650751e-01, 1.42205585e-01, 1.94441277e-01, 9.73882768e-03,
        3.27882447e-01, 2.76348042e-01],
       [3.80084730e-01, 4.93039938e-01, 4.21884083e-02, 6.91266336e-01,
        2.39019716e-01, 6.81745022e-01, 4.66814017e-01, 8.92144594e-01,
        9.36944620e-01, 8.57087017e-01],
       [4.46330168e-01, 5.97265565e-01, 4.75358351e-01, 4.48323442e-02,
        1.60935678e-01, 4.01082304e-01, 5.44070379e-01, 8.35847587e-01,
        4.22094948e-01, 1.19651234e-01],
       [6.32086786e-01, 5.17295813e-01, 3.85369685e-01, 4.23636068e-01,
   

In [27]:
np.max(arr5)

np.float64(0.9832645617372107)

In [28]:
np.min(arr5)

np.float64(0.000909187127985156)

# 14. Create a random vector of size 30 and find the mean value

In [30]:
arr6 = np.random.random(30)

In [31]:
arr6.mean()

np.float64(0.46678451393988685)